# Python Review

Goals
- recall basic Python vocabulary

## Libraries and packages

**library**: a colletion of code that we can use to perform specific tasks in our programs.

**NumPy**:
- core library for numerical computing in Python
- many other libraries use NumPy arrays as building blocks
- computations o NumPy are optimized for speed and memory usage

Let's import NumPy with **standard abbreviation**

In [1]:
import numpy as np

## Variables

**variables**: a name we assign to a particular object in Python

Example:

In [2]:
# Assign a small array to a variable a
a = np.array([[1,1,2], [3,5,8]])

In [3]:
# Run cell with the variables name to show value
a

array([[1, 1, 2],
       [3, 5, 8]])

In [4]:
# Use `print` function to print the value
print(a)

[[1 1 2]
 [3 5 8]]


## Objects

**object**: (informally speaking) is a bundle of *properties* and *actions* about something specific.

Example: 

Object: data frame

Properties: number rows, names of the columns, date created

Actions: selecting a specific row, adding a new column

A variable is the name we give a specific object, and the same object can be refrenced by different variables.

In practice, we can often use variable ad object interchangeably.

## Types

Every object in Python has a **type**. The type tells what kind of object it is.

We can also call the type of an object, the class of an object, so class and type both mean what kind of object we have.

In [5]:
print(a) 

# Check the type/class of a variable/object by using `type` function
type(a)

[[1 1 2]
 [3 5 8]]


numpy.ndarray

In [6]:
print(a[0, 0])

# Check the type on an entry on the array by indexing
type(a[0, 0])

1


numpy.int64

Notice that `type(a[0,0])` is a `numpy.int64` and not just the standard Python integer type.
This is telling us that 1 ia an integer stored as 64-bit number.

In [8]:
print(a[1, 1])

5


## Functions

`print` was our first example of a Python **function**.

Functions take in a set of **arguments** separated by commas, and use those arguments to create an output.
There are several built-in funcions in Python, most of them are for interacting with the Python basic data types such as int (integers), float (decimal numbers), str (strings), and bool (boolean values).

In [9]:
?print

Signature: print(*args, sep=' ', end='\n', file=None, flush=False)
Docstring:
Prints the values to a stream, or to sys.stdout by default.

sep
  string inserted between values, default a space.
end
  string appended after the last value, default a newline.
file
  a file-like object (stream); defaults to the current sys.stdout.
flush
  whether to forcibly flush the stream.
Type:      builtin_function_or_method

This information is a **docstring**.

A function has two type of arguments:

- **non-optional argument**: arguments **you** need to specify for the function to do something

- - **optional argument**: arguments that are pre-filled with a default value by the function, but you can override them. Optional arguments appear inside the parenthesis () in the form `optional_argument = default_value.`

In [10]:
print('changing the default end argument', end=' :)')

changing the default end argument :)

## Attributes and methods

An object in Python has attributes and methods.

- **attribute**: a property of the object, some piece of information about it
- **method**: a procedure associated with an object, so it is an action where the main ingredient is the object


#### Check in
FISH
- Attributes: length, color, species
- Method: die(), swim(), bite()

**Example**
Attributes for `numpy.arrays`

We can access a variable's attributes and methds by adding a period `.` at the end of the variable's name.

`variable.method()` or `variable.attribute`

In [12]:
a.shape

(2, 3)

In [13]:
type(a.shape)

tuple

In [14]:
a

array([[1, 1, 2],
       [3, 5, 8]])

In [15]:
# Methods examples
# min() returns the minimum value along a specified axis
a.min(axis=0)

array([1, 1, 2])

## Check-in

We can also call the `min` method without any parameters:

In [17]:
a.min()

1

#### Remember: methods are functions associated with an object

In [18]:
type(a.min)

builtin_function_or_method

## Exercise

1. Read the `print` function help. What is the **type** of the argument `sep`? Is this an optional or non-optional argument? Why?

2. Create two new variables, one with the integer value 77 and another one with the string 99.

3. Use your variables to print `77%99%77` by changing the vaules of one of the optional arguments in `print`.

In [21]:
# Answer 1
# optional argument
# sep
  # string inserted between values, default a space
    # type is string type

# Answer 2
a = 77
b = '99'

# Answer 3
print(a,b,a, sep='%')

77%99%77
