# Python Review

Goals
- recall basic Python vocabulary

## Libraries and packages

**library**: a colletion of code that we can use to perform specific tasks in our programs.

**NumPy**:
- core library for numerical computing in Python
- many other libraries use NumPy arrays as building blocks
- computations o NumPy are optimized for speed and memory usage

Let's import NumPy with **standard abbreviation**

In [1]:
import numpy as np

## Variables

**variables**: a name we assign to a particular object in Python

Example:

In [4]:
# Assign a small array to a variable a
a = np.array([[1,1,2], [3,5,8]])

In [5]:
# Run cell with the variables name to show value
a

array([[1, 1, 2],
       [3, 5, 8]])

In [6]:
# Use `print` function to print the value
print(a)

[[1 1 2]
 [3 5 8]]


## Objects

**object**: (informally speaking) is a bundle of *properties* and *actions* about something specific.

Example: 

Object: data frame

Properties: number rows, names of the columns, date created

Actions: selecting a specific row, adding a new column

A variable is the name we give a specific object, and the same object can be refrenced by different variables.

In practice, we can often use variable ad object interchangeably.